---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: extendedjobs.fissile.cloudfoundry.org
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: fissile.cloudfoundry.org
  names:
    kind: ExtendedJob
    listKind: ExtendedJobList
    plural: extendedjobs
    singular: extendedjob
  scope: Namespaced
  version: v1alpha1
